import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import ToastProvider from "@/components/providers/toaster-provider";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    // we use clerk as session provider
    // clerk for sign-in sign-up
    <ClerkProvider>
    <html lang="en">
      <ToastProvider/>
      <body className={inter.className}>{children}</body>
    </html>
    </ClerkProvider>
  );
}
